language: python

install: pip install -U tox
script: tox -v

jobs:
  include:
    - stage: test
      python: 2.7
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
      dist: xenial

    - stage: coverage
      python: 3.4
      env: TOXENV=cov
      before_script: pip install -U coveralls
      after_success: coveralls

    - stage: deploy
      python: 3.4
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: renatahodovan
        password:
          secure: cv69l4WQtvWn/kAe750iDllw6I8ex14//QvBCYBpNV9CzF6z5YiWLyL9w8OIyP7sBCAOyBzHD2Lg0NFqLfqWx2UrgrE2jHdafSRC14x1gTcoojI0hj02RrYY8/4//AK0Rk7My1LgsFNQ0jOl9pG5rdM3HgwX2HrtlPZidAu/tu4HBgD2eTYJ8LedCAqcHVKvsddPYiMlFN9R8sNc3q43KYTt86NeuX43QuyyD1Lg4+wrZPDVh0rpWUcJDLYs/xKLoeB2dudn5fxVXZIrsyVtX00G9B0TiSNaa3Bqay+qf3lZ1Xrv/r5GpkF9FjBSHqi8YliUXqxaQ3S1qPR9huM1LLzXCVwdzp8LZTUxs4wa3q5c5xXe58evOksjpw54f848mdNJ1C1fqK3P/WrVorwd7ieYPAi23ZOgGyURG5lD/u7yddzvuc6gMvFgC+OsiWv5MYBOLfKykIwpsIS98dMuQ3c2HW58yslAf084JlM+33QpZMDeSDYn/2osNBY756KpKdgDq6Qa/jewuQ/97AdZGDOZ2Zd6Elhh3+zu4eHCB5J5dDErCtHCcnjh+2nCRGRaFTSVOFkOwtGUCWIUXg+I39kz8to97+UfK84i/DWyOXVmJvFq0Q8Tqf6ouqVY21RVZRjjF8dqsBQtEUW6ZdqIriGYrCFnjPYs8T1/58XpGmk=
        on:
          repo: renatahodovan/picire
          tags: true
